### PR TITLE
Fixes several null pointers.

### PR DESCRIPTION
**Pull request by sboorlagadda**
Setting country_code in user object before calling getRootByCode(countryCode) at several places.

### CODE REVIEW

**Comment by sboorlagadda** [comment]
This may not fix issue #2, but fixes several null pointers.

**Comment by vibgy** [comment]
@johncordeiro This PR is open since 21 days now. Could you please take a look. Also please look at other open issues. Will appreciate a quicker turnaround. This is an interesting repo. It deserves some love :).

**Comment by vibgy** [comment]
Thanks @johncordeiro. Btw, great work you guys. Can you please update the license for this repo? I would love to use some parts and contribute some interesting features.

**Comment by johncordeiro** [comment]
Thanks @vibgy. We will update the license as soon as possible.

**Pull request merged**
